//! The identifier newtypes themselves.
//!
//! All four share one shape — a validated `String` — so they are generated by
//! a local macro rather than written out four times. They stay distinct types
//! so a [`SnapshotId`] can never be passed where a [`BoxId`] is expected.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Deserializer, Serialize};

use crate::error::Result;
use crate::identity::validate;

/// Define a validated identifier newtype.
///
/// Each generated type gets `new`, `as_str`, `Display`, `FromStr`, and
/// `AsRef<str>`, all delegating to [`validate`] with a fixed `kind` label that
/// appears in error messages.
macro_rules! identifier {
    ($(#[$meta:meta])* $name:ident, $kind:literal) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
        #[serde(transparent)]
        pub struct $name(String);

        impl<'de> Deserialize<'de> for $name {
            /// Applies the same validation as the constructor, so a
            /// hand-edited store file cannot reintroduce an identifier that
            /// would otherwise have been rejected.
            fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
            where
                D: Deserializer<'de>,
            {
                let value = String::deserialize(deserializer)?;
                Self::new(value).map_err(serde::de::Error::custom)
            }
        }

        impl $name {
            #[doc = concat!("Validate `value` as a ", $kind, ".")]
            ///
            /// # Errors
            ///
            /// Returns [`Error::InvalidIdentifier`](crate::error::Error::InvalidIdentifier)
            /// when `value` is empty, longer than 64 characters, or contains a
            /// character outside `[A-Za-z0-9._-]`.
            pub fn new(value: impl Into<String>) -> Result<Self> {
                let value = value.into();
                validate($kind, &value)?;
                Ok(Self(value))
            }

            #[doc = concat!("Borrow this ", $kind, " as a string slice.")]
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.0
            }

            #[doc = concat!("Consume this ", $kind, ", returning the owned text.")]
            #[must_use]
            pub fn into_string(self) -> String {
                self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str(&self.0)
            }
        }

        impl AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }

        impl FromStr for $name {
            type Err = crate::error::Error;

            fn from_str(value: &str) -> Result<Self> {
                Self::new(value)
            }
        }
    };
}

identifier!(
    /// Identifies one box within a sandbox.
    BoxId,
    "box id"
);

identifier!(
    /// Identifies one captured snapshot.
    ///
    /// A named template is simply a snapshot with a memorable id, which is why
    /// templates need no separate type.
    SnapshotId,
    "snapshot id"
);

identifier!(
    /// Names a saved template.
    ///
    /// A template is a named snapshot, so this is the only thing a template
    /// really is beyond the snapshot it points at.
    TemplateName,
    "template name"
);

identifier!(
    /// Names a registered [`Host`](crate::runtime::Host) — the machine a
    /// process runs on, such as `local` or `ssh-builder-01`.
    HostRef,
    "host reference"
);

identifier!(
    /// Names a registered [`Sandbox`](crate::runtime::Sandbox) — the
    /// confinement wrapped around a process, such as `docker` or `namespace`.
    SandboxRef,
    "sandbox reference"
);
